name: .NET周报投稿
description: "向.NET周报投稿，将会在下一期的.NET周报中展示"
title: "[投稿]:"
labels: [投稿]
body:
  - type: markdown
    attributes:
      value: 欢迎向下一期的.NET周报投稿
  - type: input
    attributes:
      label: 标题
      description: 请填写标题
      placeholder: 10-50字以内
    validations:
      required: true
  - type: textarea
    attributes:
      label: 链接
      description: 请填写指向投稿内容的链接
      placeholder: 如：https://github.com/InCerryGit/.NET-Weekly
    validations:
      required: true
  - type: textarea
    attributes:
      label: 简介
      description: 请填写关于投稿内容的简介
      placeholder: 50-200字之间
    validations:
      required: true
